
import React, { useState } from 'react';
import { CheckIcon, ChevronRightIcon, KeyRoundIcon, PlusIcon, UsersIcon } from 'lucide-react';
import { BottomNav, NavTab } from '@/shared/ui/molecules/BottomNav';
import { Badge } from '@/shared/ui/atoms/Badge';
import { MadeDexId, MadeParticipant } from './types';

export type { MadeDexId } from './types';

interface Props {participants: Record<MadeDexId, MadeParticipant[]>;onOpenDex: (id: MadeDexId) => void;onJoinWithCode: () => void;onTab: (tab: NavTab) => void;}
const DEXES: Array<{id: MadeDexId;emoji: string;title: string;detail: string;cards: string;color: string;}> = [{ id: 'date', emoji: '💑', title: '우리의 데이트 도감', detail: '둘이 함께 채우는 맛있는 기록', cards: '8장', color: 'bg-rose-100 text-rose-600' }, { id: 'lunch', emoji: '🍱', title: '회사 점심 도감', detail: '이번 달 우리 팀의 점심 메뉴', cards: '13장', color: 'bg-orange-100 text-orange-600' }];
export function MadeDexList({ participants, onOpenDex, onJoinWithCode, onTab }: Props) {const [createOpen, setCreateOpen] = useState(false);const [created, setCreated] = useState(false);return <div className="flex h-full flex-col bg-cream-100"><header className="px-5 pb-2 pt-4"><h1 className="font-display text-xl text-brown">제작 도감</h1><p className="mt-1 text-sm text-brown-soft">함께 만든 도감을 둘러보세요</p></header><main className="no-scrollbar flex-1 overflow-y-auto px-5 py-4"><div className="space-y-3">{DEXES.map((dex) => <button key={dex.id} onClick={() => onOpenDex(dex.id)} className="flex w-full items-center gap-3 rounded-2xl bg-white p-4 text-left shadow-soft active:scale-[0.99]"><span className={`flex h-14 w-14 items-center justify-center rounded-2xl text-3xl ${dex.color}`}>{dex.emoji}</span><span className="min-w-0 flex-1"><span className="block truncate font-display text-lg text-brown">{dex.title}</span><span className="mt-1 block truncate text-xs text-brown-soft">{dex.detail}</span><span className="mt-2 flex items-center gap-2"><span className="flex -space-x-2">{participants[dex.id].map((person) => <Badge key={person.id} variant="member" className="h-6 w-6" label={`참여자 ${person.name}`}>{person.name}</Badge>)}</span><span className="text-xs text-brown-soft">{participants[dex.id].length}명 · {dex.cards}</span></span></span><ChevronRightIcon size={18} className="text-brown-muted" /></button>)}</div><button onClick={onJoinWithCode} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl border border-orange-300 bg-white py-4 text-sm font-bold text-orange-600"><KeyRoundIcon size={17} />초대 코드로 참여</button>{createOpen ? <div className="mt-5 rounded-2xl border-2 border-orange-300 bg-white p-4 shadow-soft"><p className="font-display text-lg text-brown">새 도감 만들기</p><input aria-label="새 도감 이름" placeholder="도감 이름을 입력하세요" className="mt-3 w-full rounded-xl border border-cream-300 px-3 py-3 text-sm outline-none focus:border-orange-400" /><div className="mt-3 flex gap-2"><button onClick={() => setCreateOpen(false)} className="min-h-touch flex-1 rounded-xl border border-cream-300 text-sm font-medium text-brown-soft">취소</button><button onClick={() => {setCreated(true);setCreateOpen(false);}} className="min-h-touch flex-1 rounded-xl bg-orange-500 text-sm font-bold text-white">만들기</button></div></div> : <button onClick={() => setCreateOpen(true)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-orange-400 bg-orange-50 py-4 text-sm font-bold text-orange-600"><PlusIcon size={18} />새 도감 만들기</button>}{created && <p className="mt-3 flex items-center justify-center gap-1 text-xs font-medium text-orange-600"><CheckIcon size={14} />새 도감 초안을 만들었어요.</p>}<div className="mt-4 flex items-start gap-2 rounded-2xl bg-cream-200 p-3 text-xs text-brown-muted"><UsersIcon size={16} className="mt-0.5 shrink-0 text-brown-soft" />초대 코드로 참여하면 함께 카드를 등록할 수 있어요.</div></main><BottomNav active="제작" onTab={onTab} /></div>;}