




import React, { useState } from 'react';
import { ArrowLeftIcon, CheckIcon, ClipboardIcon, CopyIcon, UsersIcon } from 'lucide-react';

import { Badge } from '@/shared/ui/atoms/Badge';
import { MadeParticipant } from './types';

export type { MadeParticipant } from './types';

interface Props {dexTitle: string;code: string;participants: MadeParticipant[];onBack: () => void;onCopy: () => void;onRemove: (id: string) => void;}

export function MadeDexInvite({ dexTitle, code, participants, onBack, onCopy, onRemove }: Props) {const [copied, setCopied] = useState(false);const [removing, setRemoving] = useState<MadeParticipant | null>(null);const copy = () => {onCopy();setCopied(true);window.setTimeout(() => setCopied(false), 1800);};
  return <div className="flex h-full flex-col bg-cream-100"><header className="flex items-center gap-3 px-5 py-4"><button onClick={onBack} aria-label="뒤로가기"><ArrowLeftIcon size={22} /></button><span className="font-display text-lg text-brown">참여자 관리</span></header><main className="no-scrollbar flex-1 overflow-y-auto px-5"><section className="rounded-3xl bg-orange-500 p-5 text-center text-white shadow-card"><p className="text-sm font-medium text-orange-100">{dexTitle} 전용 초대 코드</p><p className="mt-3 font-display text-3xl tracking-[0.28em]">{code}</p><button onClick={copy} className="mt-4 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-orange-600">{copied ? <CheckIcon size={16} /> : <CopyIcon size={16} />} {copied ? '복사했어요' : '코드 복사하기'}</button><p className="mt-3 text-xs text-orange-50">코드는 7일 동안 유효해요. 카톡이나 문자로 전달해 보세요.</p></section><section className="mt-5"><div className="flex items-center gap-2"><UsersIcon size={18} className="text-orange-500" /><h2 className="font-display text-lg text-brown">참여자 {participants.length}명</h2></div><div className="mt-3 space-y-2">{participants.map((participant) => <article key={participant.id} className="flex items-center gap-3 rounded-2xl bg-white p-3 shadow-soft"><Badge variant="member" className="h-10 w-10 border-0 text-sm" label={`참여자 ${participant.name}`}>{participant.name}</Badge><span className="flex-1 text-sm font-bold text-brown">{participant.name}님</span>{participant.id !== 'me' && <button onClick={() => setRemoving(participant)} className="min-h-touch rounded-full bg-cream-200 px-4 text-xs font-bold text-brown-soft">삭제</button>}</article>)}</div></section><section className="mt-5 rounded-2xl bg-white p-4 text-sm text-brown-soft shadow-soft"><ClipboardIcon size={18} className="mb-2 text-orange-500" />코드를 받은 친구는 제작 도감 목록에서 <strong className="text-brown">초대 코드로 참여</strong>를 선택해 입력할 수 있어요. 내보내도 기존에 등록한 카드는 그대로 남아요.</section></main>{removing && <div className="absolute inset-0 z-20 flex items-center justify-center bg-black/35 px-5"><section role="dialog" aria-modal="true" className="w-full rounded-3xl bg-cream-50 p-5 shadow-pop"><h2 className="font-display text-xl text-brown">참여자를 내보낼까요?</h2><p className="mt-2 text-sm text-brown-soft">{removing.name}님을 도감에서 내보낼까요?<br />기존에 등록한 카드는 유지됩니다.</p><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => setRemoving(null)} className="rounded-2xl bg-cream-200 py-3 text-sm font-bold text-brown-soft">취소</button><button onClick={() => {onRemove(removing.id);setRemoving(null);}} className="rounded-2xl bg-orange-500 py-3 text-sm font-bold text-white">내보내기</button></div></section></div>}</div>;
}

export function MadeDexCodeEntry({ onBack, onJoin }: {onBack: () => void;onJoin: (code: string) => 'success' | 'invalid' | 'expired' | 'already';}) {const [code, setCode] = useState('');const [status, setStatus] = useState<'invalid' | 'expired' | 'already' | null>(null);const submit = () => {const result = onJoin(code.toUpperCase());if (result !== 'success') setStatus(result);};
  const message = status === 'invalid' ? '존재하지 않는 초대 코드예요.' : status === 'expired' ? '만료된 초대 코드예요. 새 코드를 요청해 주세요.' : status === 'already' ? '이미 이 제작 도감에 참여 중이에요.' : '';
  return <div className="flex h-full flex-col bg-cream-100"><header className="flex items-center gap-3 px-5 py-4"><button onClick={onBack} aria-label="뒤로가기"><ArrowLeftIcon size={22} /></button><span className="font-display text-lg text-brown">초대 코드로 참여</span></header><main className="flex-1 px-5 pt-8"><div className="rounded-3xl bg-white p-5 text-center shadow-soft"><span className="text-4xl">🤝</span><h1 className="mt-3 font-display text-xl text-brown">친구의 제작 도감에 참여해요</h1><p className="mt-2 text-sm leading-5 text-brown-muted">초대받은 6자리 코드를 입력하면<br />함께 카드를 등록할 수 있어요.</p><input value={code} onChange={(event) => {setCode(event.target.value.replace(/[^a-zA-Z0-9]/g, '').slice(0, 6));setStatus(null);}} placeholder="ABC123" className="mt-6 w-full rounded-2xl border-2 border-cream-300 bg-cream-50 px-4 py-4 text-center font-display text-2xl uppercase tracking-[0.22em] outline-none focus:border-orange-400" />{status && <p className="mt-2 text-sm text-red-500">{message}</p>}</div></main><div className="px-5 pb-8"><button disabled={code.length !== 6} onClick={submit} className="w-full rounded-2xl bg-orange-500 py-4 font-display text-lg text-white shadow-card disabled:opacity-40">도감 참여하기</button></div></div>;}